# Generated by Django 2.2.5 on 2020-02-05 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice',
            new_name='Stat',
        ),
        migrations.RenameModel(
            old_name='Question',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='question_text',
            new_name='user_name',
        ),
    ]
