# Generated by Django 2.2.5 on 2020-03-29 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_session_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='date',
        ),
        migrations.AddField(
            model_name='analysis',
            name='sleepDisruptions',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='analysis',
            name='sleepNotes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='analysis',
            name='sleepQuality',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='UserInput',
        ),
    ]
