# Generated by Django 2.2.5 on 2020-02-12 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_dummy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dummy',
        ),
    ]
