# Generated by Django 2.2.5 on 2020-03-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20200329_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='status',
            field=models.TextField(default=''),
        ),
    ]
