# Generated by Django 2.2.5 on 2020-02-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_delete_dummy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dummy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(default=0)),
                ('hr', models.IntegerField(default=0)),
                ('rr', models.IntegerField(default=0)),
            ],
        ),
    ]
