# Generated by Django 2.2.5 on 2020-03-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_dummy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
