# Generated by Django 2.2.5 on 2020-03-19 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20200309_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('tst', models.TimeField()),
                ('avgHR', models.IntegerField(default=0)),
                ('avgRR', models.IntegerField(default=0)),
                ('avgHRdip', models.IntegerField(default=0)),
                ('minHR', models.IntegerField(default=0)),
                ('maxHR', models.IntegerField(default=0)),
                ('minRR', models.IntegerField(default=0)),
                ('maxRR', models.IntegerField(default=0)),
                ('sleepQuality', models.IntegerField(default=0)),
                ('numSleepDisruptions', models.IntegerField(default=0)),
                ('sleepDisruptions', models.TextField()),
                ('sleepNotes', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.User')),
            ],
        ),
    ]
