# Generated by Django 2.2.5 on 2020-04-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20200401_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='dailyHR',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysis',
            name='dailyRR',
            field=models.IntegerField(default=0),
        ),
    ]
