# Generated by Django 2.2.5 on 2020-03-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_vitals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='time',
            field=models.DateTimeField(verbose_name='date published'),
        ),
        migrations.DeleteModel(
            name='Vitals',
        ),
    ]
