# Generated by Django 2.2.5 on 2020-03-22 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_analysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleepQuality', models.IntegerField(default=0)),
                ('sleepDisruptions', models.TextField()),
                ('sleepNotes', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='sleepDisruptions',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='sleepNotes',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='sleepQuality',
        ),
    ]
