# Generated by Django 2.2.5 on 2020-03-22 22:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20200322_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinput',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinput',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.User'),
            preserve_default=False,
        ),
    ]
