# Generated by Django 2.2.5 on 2020-04-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20200406_0301'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='analysis',
            name='sleepQuality',
            field=models.IntegerField(default=3),
        ),
    ]
