# Generated by Django 2.2.5 on 2020-03-22 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20200322_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='tst',
            field=models.DurationField(),
        ),
    ]
